var datax = [
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales especializados de asesoria juridica en materia contractual que sean sometidos a su consideracion en los proceso que adelante el municipio de zipaquira cundinamarca apotando para ello sus conocimiento y experticia para el logro de los fines perseguidos por la entidad territorial",
    "presupuesto": 64166666,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales especializados para la asesoria en la gestion territorial del plan de desarrollo municipal a� o sicep y siee en la alcaldia municipal de zipaquira",
    "presupuesto": 57500000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 1,
    "3": 2,
    "4": 1,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el fortalecimiento de la secretaria de planeacion direccion de ordenamiento territorial y sistemas de informacion en el banco de proyectos de inversion para la formulacion revision y estructuracion de proyectos de inversion del pgn sgr en la metodologia mga",
    "presupuesto": 34500000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "suministro de personal en mision no calificado para las instituciones educativas del municipio de zipaquira",
    "presupuesto": 33094850,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "suministro de personal en mision no calificado para las diferentes dependencias de la alcaldia de zipaquira",
    "presupuesto": 26314308,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "suministro de personal para el funcionamiento y aseo de la terminal de transportes de zipaquira",
    "presupuesto": 18875883,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 2,
    "3": 3,
    "4": 1,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la administracion depuracion de la base de datos y reporte de informacion de los sistemas de informacion requeridas para el funcionamiento el banco de proyectos de inversion de la direccion de ordenamiento territorial y sistemas de informacion de la secretaria de planeacion",
    "presupuesto": 21849672,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la defensa judicial y asesoria juridica del municipio de zipaquira",
    "presupuesto": 53790000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de un inmueble para el funcionamiento de la oficina de transporte y movilidad",
    "presupuesto": 47124000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 2,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de vigilancia y seguridad privada para amparar los bienes del municipio de zipaquira o aquellos que se encuentren a su cargo",
    "presupuesto": 24055488,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la elaboracion y estructuracion de los analisis del sector economico de los diferentes procesos de contratacion que adelanta el municipio de zipaquira cundinamarca",
    "presupuesto": 15000000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "convenio interadministrativo celebrado entre los municipios de zipaquira y girardot para el traslado de la docente al servicio de la educacion estatal",
    "presupuesto": 0,
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo logistico para la realizacion del seminario de actualizacion del nuevo codigo nacional de policia y convivencia decreto del de julio de",
    "presupuesto": 30000000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 4,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la coordinacion del centro integral de servicios asesoria y apoyo a los programas de adulto mayor y discapacidad de la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 36750000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la atencion integral proteccion social y residencia permanente para personas mayores en alto grado de vulnerabilidad del municipio de zipaquira vigencia",
    "presupuesto": 106400000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para adelantar procesos de contratracion en las etapas precontractual contractual y post contractual del municipio de zipaquira",
    "presupuesto": 36750000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "aunar esfuerzos tecnicos humanos financieros y operativos para la atencion integral de ni� os y ninas de los jardines sociales barandillas coclies san miguel vigencia",
    "presupuesto": 335544653,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para toma de datos y atencion de usuarios que requieren sisben en el municipio de zipaquira zona urbana y rural",
    "presupuesto": 14700000,
    "Categoria": "Nuestro futuro, la transformaci�n del campo"
  },
  {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para toma de datos y atencion de usuarios que requieren sisben en el municipio de zipaquira zona urbana y rural",
    "presupuesto": 14700000,
    "Categoria": "Nuestro futuro, la transformaci�n del campo"
  },
  {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para toma de datos y atencion de usuarios que requieren sisben en el municipio de zipaquira zona urbana y rural",
    "presupuesto": 14700000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para realizar el registro fotografico de las actividades adelantadas en la ejecucion de los planes programas y proyectos del municipio de zipaquira",
    "presupuesto": 7350000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para toma de datos y atencion de usuarios que requieren sisben en el municipio de zipaquira zona urbana y rural",
    "presupuesto": 14700000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el area de ordenamiento territorial y sistemas de informacion en la recoleccion organizaci� n y digitacion de informacion del sistema unico de informacion sui",
    "presupuesto": 14700000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de ingeniero a de alimentos para la ejecucion del programa de alimentacion escolar en la vigencia",
    "presupuesto": 27500000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 1,
    "3": 2,
    "4": 1,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la ejecucion de actividades tecnico operativas destinadas a la conservacion catastral urbana y rural del municipio de zipaquira en el marco del convenio del suscrito con el instituto geografico agustin codazzi igac",
    "presupuesto": 19950000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 1,
    "2": 1,
    "3": 2,
    "4": 1,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la ejecucion de actividades tecnico operativas destinadas a la conservacion catastral urbana y rural del municipio de zipaquira en el marco del convenio del suscrito con el instituto geografico agustin codazzi igac",
    "presupuesto": 19950000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la atencion integral proteccion social y residencia permanente para personas mayores en alto grado de vulnerabilidad en el municipio de zipaquira vigencia",
    "presupuesto": 44800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la atencion integral proteccion social y residenicia permanente para personas mayores en algo grado de vulnerabilidad del municipio de zipaquira vigencia",
    "presupuesto": 112000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la defensa judicial y asesoria juridica del municipio de zipaquira",
    "presupuesto": 52160000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "suministro de fotocopias en blanco y negro full color anillados laminados y fotoplanos para las diferentes dependencias de la alcaldia municipal de zipaquira",
    "presupuesto": 30000000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 2,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de vigilancia y seguridad privada para amparar los bienes del municipio de zipaquira o aquellos que se encuentran a su cargo",
    "presupuesto": 603988797,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 3,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para asistir administrativa y financieramente los procesos presupuestales contables y de tesoreria en la secretaria de hacienda del municipio de zipaquira",
    "presupuesto": 18900000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 3,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para asistir administrativa y financieramente los procesos presupuestales contables y de tesoreria en la secretaria de hacienda del municipio de zipaquira",
    "presupuesto": 19950000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 3,
    "4": 1,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en las actividades asistenciales de la direccion urbanismo y vivienda de la secretaria de planeacion",
    "presupuesto": 14700000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el cuidado conservacion y mantenimiento de los predios de interes hidrico del municipio de zipaquira",
    "presupuesto": 16485000,
    "Categoria": "Crecimiento verde, un ambiente para todos"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el cuidado conservacion y mantenimiento de los predios de interes hidrico del municipio de zipaquira",
    "presupuesto": 16485000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion como tecnologo en regencia de farmacia para el seguimiento y asistencia tecnica al servicio farmaceutico droguerias y tiendas naturistas del municipio de zipaquira vigencia",
    "presupuesto": 21000000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 1,
    "2": 1,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo de los programas de la secretaria de transporte y movilidad del municipio de zipaquira",
    "presupuesto": 14280000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 2,
    "2": 1,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en el desarrollo de los programas y actividades de seguridad vial de la secretaria de transporte y movilidad en el municipio de zipaquira",
    "presupuesto": 19740000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 2,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de trabajador social para la ejecucion de los programas de alimentacion escolar en la vigencia",
    "presupuesto": 23000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de un nutricionista para la ejecucion de los programas de alimentacion escolar en la vigencia",
    "presupuesto": 39500000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en los procesos de cobro persuasivo adelantados por la direccion de rentas y jurisdiccion coactiva de la secretaria de hacienda municipal",
    "presupuesto": 26250000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 1,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la implementacion y seguimiento de la estrategia de gobierno en linea en el municipio de zipaquira",
    "presupuesto": 29795810,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para acompa� ar a la secretaria general en el proceso de manejo del pasivo pensional del municipio de zipaquira",
    "presupuesto": 35189968,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 0,
    "6": 3,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en la descongestion de los procesos administrativos coactivos de la direccion de rentas y jurisdiccion coactiva de la secretaria de hacienda municipal",
    "presupuesto": 26250000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 2,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la asistencia tecnica y auditoria integral a prestadores de servicios de salud en el sistema obligatorio de garantia de calidad sogc del municipio de zipaquira vigencia",
    "presupuesto": 36750000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 2,
    "2": 1,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en el desarrollo de los programas y actividades de seguridad vial de la secretaria de transporte y movilidad en el municipio de zipaquira",
    "presupuesto": 19740000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el cuidado conservacion y mantenimiento de los predios de interes hidrico del municipio de zipaquira",
    "presupuesto": 16485000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 1,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en ingenieria de alimentos para realizar las actividades de la dimension de la salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 24990000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 2,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para realizar acciones de la dimension de salud publica en emergencias y desastres del municipio de zipaquira vigencia",
    "presupuesto": 21860000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 1,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el acompa� amiento para la direccion de rentas y jurisdicion coactiva de la secretaria de hacienda",
    "presupuesto": 12000000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 4,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en fisioterapia para la ejecucion de los programas dirigidos a la poblacion adulto mayor y discapacidad de la secretaria de salud y proteccion social vigencia",
    "presupuesto": 24717000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en salud publica para desarrollar acciones administrativas relacionadas con el centro de acopio municipal para la vigencia",
    "presupuesto": 16100000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en ingenieria de alimentos para realizar las actividades de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 24990000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 4,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo del programa de participacion social de la secretaria de salud y proteccion social vigencia",
    "presupuesto": 11900000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 2,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la atencion a la poblacion beneficiaria del programa mas familias en accion del departamento para la prosperidad social dps en el municipio de zipaquira vigencia",
    "presupuesto": 17850000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 24990000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la propagacion vegetal manejo foretal cambio climatico y conservacion de los recursos naturales",
    "presupuesto": 35000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el control de obra y elaboracion de proyectos de infraestructura en la secretaria de obras publicas del municipio de zipaquira",
    "presupuesto": 20666666,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 2,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 4,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales especializados para brindar asesoria a los procesos administrativos de gestion y realizar seguimiento a los procesos de aseguramiento en salud en el municipio de zipaquira para la vigenica",
    "presupuesto": 52000000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "aunar esfuerzos adminsitrativos y financieros para la transferencia de recursos que se apropien para la sobretasa bomberil destinados a atender las necesidades del cuerpo de bomberos voluntarios zipaquira para la atencion a rescates emergencias y demas calamidades conexas que se presenten en el municipio de zipaquira",
    "presupuesto": 477593433,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 24990000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la ejecucion de procesos operativos y asistenciales dirigidos al fortalecimiento de la oficina del sisben del municipio de zipaquira",
    "presupuesto": 14560000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en fonoaudiologia para el programa dirigido a la poblacion con discapacidad y nee adelantados por la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 9416000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 2,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en medicina veterinaria para realizar el control de poblacion canina y felina del municipio de zipaquira vigenica",
    "presupuesto": 23800000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 1,
    "5": 0,
    "6": 3,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en la gestion en la descongestion de los procesos administrativos coactivos de la direccion de rentas y jurisdiccion coactiva de la secretaria de hacienda municipal",
    "presupuesto": 25000000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 2,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en medicina veterinaria para realizar el control de poblacion canina y felina del municipio de zipaquira vigenica",
    "presupuesto": 23800000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la evaluacion del cumplimiento de las normas urbanisticas en el centro administrativo municipal integrado de barandillas c a m i en el area de urbanismo y vivienda de la secretaria de planeacion",
    "presupuesto": 27580245,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de un inmueble para el funcionamiento de la comisaria segunda de familia del municipio de zipaquira",
    "presupuesto": 55580000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de un inmueble ubicado en el barrio san miguel para el funcionamiento del punto vive digital de zipaquira",
    "presupuesto": 21000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 3,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el desarrollo de acciones de la dimension de fortalecimiento de la autoridad sanitaria vigilancia epidemiologica del municipio de zipaquira para la vigencia",
    "presupuesto": 33418350,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 4,
    "2": 3,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales con el proposito de brindar asistencia tecnica realizar el control y seguimiento administrativo presupuestal y contable del fondo local de salud y apoyo en el fortalecimiento de la prestacion de servicios de salud del municipio de zipaquira vigencia",
    "presupuesto": 35000000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de transporte terrestre con conductor para realizar las actividades programadas por las diferentes dependencias de la alcaldia municipal de zipaquira",
    "presupuesto": 32000000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de odontologia para desarrollar acciones de salud oral en el municipio de zipaquira para la vigencia",
    "presupuesto": 21860000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la promocion de la afiliacion en aseguramiento el seguimiento a las actividades pedt res del y a los programas de calidad en salud vigencia",
    "presupuesto": 30000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de enfermeria para desarrollar acciones de salud materna en el municipio de zipaquira para la vigencia",
    "presupuesto": 21860000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en psicologia para desarrollar actividades de la dimension convivencia social y salud mental del municipio de zipaquira vigencia",
    "presupuesto": 21860000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la asistencia de las actividades orientadas a la administracion del sistema integrado de informacion para la gestion del riesgo de desastre en el municipio de zipaquira cundinamarca",
    "presupuesto": 22500000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en ciencias sociales para desarrollar acciones en la dimension de convivencia social y salud mental vigencia",
    "presupuesto": 31827000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en medicina veterinaria para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 4,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para brindar acompa� amiento a los procesos del servicio de atencion al ciudadano sac en la secretaria de salud y proteccion social vigencia",
    "presupuesto": 23000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en ingenieria de alimentos para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en ingenieria ambiental y sanitaria para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigenica",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo de actividades de las ludotecas municipales y programa infancia que adelanta la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 10200000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el funcionamiento del punto vive digital pvd municipio de zipaquira",
    "presupuesto": 15301000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en ingenieria quimica para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en medicina veterinaria para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion como conductor del vehiculo de placas odt de la secretaria de gobierno del municipio de zipaquira",
    "presupuesto": 16000000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 1,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo de actividades de las ludotecas municipales y programa infancia que adelanta la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 10200000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo de programa de sanidad animal e inseminacion artificial bovina en el municipio de zipaquira",
    "presupuesto": 19750000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 1,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para realizar seguimientos a establecimientos de belleza centros de tatuajes y piercing para la adecuada operaci� n de los servicios ofertados en zipaquira vigencia",
    "presupuesto": 21000000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 1,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en salud publica y del riesgo para desarrollar acciones de la dimension de sexualidad derechos sexuales y reproductivos del municipio de zipaquira para la vigencia",
    "presupuesto": 14000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en medicina veterinaria para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo de actividades de las ludotecas municipales y programa infancia que adelanta la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 10200000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de enfermeria para desarrollar acciones de vigilancia en pai del municipio de zipaquira vigencia",
    "presupuesto": 24237000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 1,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en medicina veterinaria para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en ingenieria de alimentos para realizar las actividades de la dimension de salud ambiental del municipio de zipaquira vigencia",
    "presupuesto": 23800000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 1,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion al acompa� amiento de la direccion de rentas y jurisdiccion coactiva de la secretaria de hacienda",
    "presupuesto": 16533333,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion como promotor campesino en el municipio de zipaquira",
    "presupuesto": 14000000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 2,
    "2": 2,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el desarrollo de los programas acompa� amiento y asistencia de la secretaria de transporte y movilidad en el desarrollo de las competencias de ley en el marco de los asuntos relacionados con la aplicaci� n normativa frente al transito y transporte del municipio de zipaqura",
    "presupuesto": 21000000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 1,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el desarrollo de programa de mujer y genero de la secretaria de salud y proteccion social vigencia",
    "presupuesto": 24717000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para brindar soporte tecnico mantenimiento y actualizacion al sistema de control y administracion del regimen subsidiado sicresub en el municipio de zipaquira vigencia",
    "presupuesto": 4500000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de enfermeria para desarrollar acciones en salud materna en el municipio de zipaquira para la vigencia",
    "presupuesto": 21860000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de enfermeria para desarrollar acciones de la dimension de vida saludable y enfermedades transmisibles del municipio de zipaquira vigencia",
    "presupuesto": 21860000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para la propagacion y produccion de material vegetal en los viveros del municipio",
    "presupuesto": 15700000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en trabajo social para desarrolllar acciones de la dimension de convivencia social y salud mental vigencia",
    "presupuesto": 21860000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en la organizaci� n de la informacion documental de la secretaria de hacienda del municipio de zipaquira",
    "presupuesto": 14000000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 1,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el sistema de informacion de las dimensiones del plan decenal de salud publica municipio de zipaquira vigencia",
    "presupuesto": 14000000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 4,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la realizacion del programa de participacion social de la secretaria de salud y proteccion social en el municipio de zipaquira vigencia",
    "presupuesto": 16000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 1,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la ejecucion de los proyectos y actividades del sistema de gestion de seguridad y salud en el trabajo de la alcaldia de zipaquira enmarcado en la aplicaci� n de lo establecido en la ley de decreto reglamentario de",
    "presupuesto": 24313120,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 1,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el sistema de informacion del proyecto vigilancia del riesgo en el ambito familiar del municipio de zipaquira para la vigencia",
    "presupuesto": 14000000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el funcionamiento del punto vive digital pvd municipio de zipaquira",
    "presupuesto": 14807420,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento del parqueadero parque la esperanza",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 5,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de la taquilla no ubicada en el terminal de transportes del municipio de zipaquira para el uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 5,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de la taquilla no ubicada en el terminal de transportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 4,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento del cubiculo no ubicado en el terminal de transportes del municipio de zipaquira para el uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 4,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento del cubiculo no ubicado en el terminal de transportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 4,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento del cubiculo no ubicado en el terminal de transportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 5,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de la taquilla no ubicada en el terminal de transportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamieto de la taquilla no ubicada en elterminal de trasnportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 5,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de la taquilla no ubicada en el terminal de transportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 4,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento del cubiculo no ubicado en el terminal de transportes del municipio de zipaquira para el uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 5,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de la taquilla no ubicada en el terminal de transportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "aunar esfuerzos administrativos y financieros para la transferencia de recursos que se apropien en el fondo de solidaridad y redistribucion de ingresos destinados a subsidiar la demanda de los servicios de acueducto y aseo por los usuarios de los estratos y del municipio de zipaquira a la empresa acueducto alcantarillado y aseo de zipaquira e s p",
    "presupuesto": "",
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el funcionamiento del centro de traslado por proteccion ctp del municipio de zipaquira",
    "presupuesto": 24500000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el funcionamiento del centro de traslado por proteccion ctp del municipio de zipaquira",
    "presupuesto": 24500000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de enfermeria para desarrollar acciones de salud sexual y reproductiva en el municipio de zipaquira para la vigencia",
    "presupuesto": 21860000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en psicologia para las actividades dirigidas a la poblacion habitante de calle y pobreza extrema adelantadas por la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 16478000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "compra de pabellones para el municipio de zipaquira",
    "presupuesto": 11805000,
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 5,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de la taquilla no ubicada en el terminal de transportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 2,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en salud publica para desarrollar acciones de la dimension de seguridad alimentaria del municipio de zipaquira vigencia",
    "presupuesto": 14000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 4,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo de estrategias de comunicaci� n para dinamizacion de los programas sociales adelantados por la secretaria de salud y proteccion social vigencia",
    "presupuesto": 11900000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para desarrollar acciones en seguridad alimentaria y nutricional del municipio de zipaquira para la vigencia",
    "presupuesto": 32534000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 4,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en psicologia para desarrollar acciones en la dimension en convivencia social y salud mental vigencia",
    "presupuesto": 21860000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 1,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en el desarrollo del programa de participacion ciudadana apoyando al consejo territorial de planeacion del municipio de zipaquira",
    "presupuesto": 14000000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 2,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en salud publica para realizar acciones de la dimension de salud y ambito laboral del municipio de zipaquira vigencia",
    "presupuesto": 20000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion par realizar el proceso de gestion documental en la secretaria de salud y proteccion social del municipio de zipaquira",
    "presupuesto": 7000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 3,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en salud publica para desarrollar acciones de la dimension de fortalecimiento de la autoridad sanitaria vigilancia epidemiologica del municipio de zipaquira para la vigencia",
    "presupuesto": 14000000,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 1,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion como guia turistico para la orientacion al visitante dentro del programa de promocion del desarrollo economico y turistico en el municipio de zipaquira",
    "presupuesto": 10200000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "interventoria tecnica administrativa y financiera para la interventoria tecnica del contrato de con sus otros si y adiciones celebrado entre la empresa de energia de bogota cedio a codensa s a esp y el municipio de zipaquira",
    "presupuesto": 42900000,
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la ejecucion de actividades del programa de juventud adelantados por la secretaria de salud y proteccion social vigencia",
    "presupuesto": 24700000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales como educadora especial para atencion a personas con discapacidad y n e e en el municipio de zipaquira vigencia",
    "presupuesto": 7062000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de trabajador social para la ejecucion del programa policial grupo de mediacion en la vigencia",
    "presupuesto": 21927866,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "entregar a titulo de comodato precario o prestamo de uso un plotter redsail ra c resolucion dpi interfaz usb",
    "presupuesto": "",
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "aunar esfuerzos tecnicos administrativos economicos y logisticos con persona juridica de derecho privado sin animo de lucro para la celebracion del dia de la mujer y genero del municipio de zipaquira vigencia",
    "presupuesto": 20000000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "compra de software especializado para ser instalado en los equipos de computo de la oficina asesora de prensa y comunicaciones de la alcaldia de zipaquira para la produccion de piezas de comunicaci� n multimedia",
    "presupuesto": 8389500,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 1,
    "2": 2,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en salud publica y del riesgo para desarrollar acciones en pai del municipio de zipaquira vigencia",
    "presupuesto": 13300000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 3,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la educacion ambiental no formal encaminados a la proteccion y conservacion de los recursos naturales y el ambiente en el municipio de zipaquira para la vigencia de",
    "presupuesto": 23750000,
    "Categoria": "Crecimiento verde, un ambiente para todos"
  },
  {
    "1": 1,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo de actividades de las ludotecas municipales y programa infancia que adelanta la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 10200000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "suministro de asfalto frio para el mantenimiento de la malla vial municipio de zipaquira",
    "presupuesto": 29971935,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de latoneria pintura y soldaduras especiales para los vehiculos maquinaria y equipos de la secretaria de obras publicas del municipio de zipaquira",
    "presupuesto": 29500000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "prestacion de servicios profesionales para el acompa� amiento en la depuracion de informacion contable garantizando la adecuada implementacion de las niif",
    "presupuesto": 38666666,
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 2,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de enfermeria para desarrollar acciones de salud materna en el municipio de zipaquira para la vigencia",
    "presupuesto": 21131000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 4,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de dos taquillas identificadas con los numeros doce a y doce b a y b ubicadas en el terminal de transportes del municipio de zipaquira para uso comercial",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "aunar esfuerzos financieros administrativos y operativos para apoyar las labores de rescate y atencion de emergencias y desastres a cargo de la defensa civil a traves de la ambulancia tab en el municipio de zipaquira",
    "presupuesto": "",
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "entrega a titulo de comodato precario o prestamo de una ambulancia tab tipo van x marca hiunday h modelo color blanco ceramica de placas ojg motor d bh chasis kmfwbx hacu",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de un inmueble para el funcionamiento de la comisaria de la familia de zipaquira",
    "presupuesto": 26605512,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "entrega a titulo de comodato precario o prestamo de uso los siguientes bienes muebles tres motocicletas marca suzuki dr x de placas ggu e ggu e comprados por el fondo de seguridad para el ejercicio de las funciones de la estacion de policia de zipaquira",
    "presupuesto": "",
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 1,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para proporcionar asistencia tecnico operativa a la secretaria de planeacion en los procesos de legalizacion de asentamientos humanos y demas actividades de representacion grafica de la superficie terrestre en el municipio de zipaquira",
    "presupuesto": 29997000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 5,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en trabajo social para la ejecucion de actividades de programa colombia mayor y banco de alimentos direccionados desde la secretaria de salud y proteccion social a la poblacion adulto mayor del municipio vigencia",
    "presupuesto": 19000000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "prestacion de servicios profesonales para la capacitacion encaminada a liderazgo y toma de decisiones de la administracion muncipal de zipaquira",
    "presupuesto": 3354000,
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "compra de pajillas de semen bovino y nitrogeno liquido e insumos propios de la actividad con destino al proyecto de mejoramiento genetico bovinos",
    "presupuesto": 12834269,
    "Categoria": "Ninguno"
  },
  {
    "1": 1,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en electromedicina para realizar actividades de la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 19333333,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 2,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion para el desarrollo de actividades conjuntas e impulso del sector artesanal dentro del marco del fortalecimiento empresarial del municipio de zipaquira",
    "presupuesto": "",
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 1,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "integrar recursos tecnicos humanos y financieros administrativos y operativos para el funcionamiento del centro de desarrollo infantil mi ranchito en el municipio de zipaquira vigencia",
    "presupuesto": "",
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "entregar a titulo de comodato precario o prestamo de uso un plotter redsail ra c resolucion dpi iterfaz usb",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "entregar a titulo de comodato precario o prestamo de uso un plotter redsail ra c resolucion dpi iterfaz usb",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales de enfermeria para desarrolla acciones en enfermedades cronicas no transmisibles en el municipio de zipaquira para la vigencia",
    "presupuesto": 19674000,
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 1,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el mantenimiento actualizacion soporte y capacitacion del software has sql compuesto por los modulos de contabilidad tesoreria control presupuestal impuesto de industria y comercio impuesto predial nomina tasas y contribuciones almacen retencion de ica contratacion activos fijos y otros",
    "presupuesto": 41565510,
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 2,
    "2": 4,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios de apoyo a la gestion en salud publica para realizar las actividades de la dimension de salud ambiental vigencia",
    "presupuesto": 15999993,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 3,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios pofesionales en psicologia para la ejecucion del programa del lgtbi adelantado por la secretaria de salud y proteccion social del municipio de zipaquira",
    "presupuesto": 21186000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 1,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales en psicologia para el desarrollo de actividades del programa adolescencia que adelanta la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 13600000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "entregar a titulo de comodato precario o prestamo de uso un plotter redsail ra c resolucion dpi iterfaz usb",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 5,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "arrendamiento de la taquilla no para uso comercial ubicado en el terminal de transportes del municipio de zipaquira",
    "presupuesto": 0,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 3,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el programa infancia que adelanta la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": 14124000,
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el soporte tecnico actualizacion mantenimiento y capacitacion de software has sql",
    "presupuesto": 27489000,
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 1,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la implementacion del programa de formacion a las comunidades educativas para la paz y el posconflicto",
    "presupuesto": "",
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 2,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para el acompa� amiento a la secretaria de planeacion en la fase de alistamiento para la aplicaci� n del cobro de valorizacion en el municipio de zipaquira",
    "presupuesto": "",
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 1,
    "2": 1,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "prestacion de servicios profesionales para la proteccion de ecosistemas estrategicos cumplimiento de la sentencia rio bogota y seguimiento a las actividades mineras",
    "presupuesto": "",
    "Categoria": "Seguridad, Convivencia, Justicia, Democracia"
  },
  {
    "1": 0,
    "2": 0,
    "3": 1,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": "FALSO",
    "Titulo": "entrega a titulo de comodato precario de las oficinas y del salon polifuncional del barrio algarra iii a la junta de accion comunal del barrio algarra iii",
    "presupuesto": "",
    "Categoria": "Competitividad y estructura, una ciudad din�mica y visionaria"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 2,
    "7": "FALSO",
    "Titulo": "suministro de tintas y tonners para las impresoras de la alcaldia de zipaquira",
    "presupuesto": "",
    "Categoria": "Un gobierno bonito, un alcalde para la gente"
  },
  {
    "1": 0,
    "2": 4,
    "3": 3,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "FALSO",
    "Titulo": "pretacion de servicios profesionales de terapeuta ocupacional para la ejecucion de los programas dirigidos a la poblacion con discapacidad de la secretaria de salud y proteccion social del municipio de zipaquira vigencia",
    "presupuesto": "",
    "Categoria": "Movilidad social, nada m�s importante que la gente"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": "VERDADERO",
    "Titulo": "",
    "presupuesto": "",
    "Categoria": "Ninguno"
  },
  {
    "1": 1018804955,
    "2": 2588907876,
    "3": 695880822,
    "4": 29400000,
    "5": 40235000,
    "6": 523472658,
    "7": 109559935,
    "Titulo": "Total",
    "presupuesto": 5006261246,
    "Categoria": 5006261246
  }
]